steps:
  - block: 'Trigger full build'
    key: 'trigger-full-build'

  - label: 'Upload the full test pipeline'
    depends_on: 'trigger-full-build'
    command: buildkite-agent pipeline upload .buildkite/pipeline.full.yml